apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer-backend
  namespace: sealos-storage-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: viewer-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: viewer-backend
    spec:
      serviceAccountName: viewer-backend
      containers:
        - name: backend
          image: sealos-storage-manager-viewer:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: viewer-backend-config
